#!/bin/sh
yarn lint-staged

ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
# git add "${FRONTEND_STAGED_FILES[@]}"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi

exit $?
