#!/bin/sh
FRONTEND_STAGED_FILES=($(git diff --diff-filter=d --cached --name-only ./src | grep -E '^.*src\/.*\.(tsx|ts)$'))

echo $FRONTEND_STAGED_FILES
STAGED_FILES=$FRONTEND_STAGED_FILES
for i in "${!STAGED_FILES[@]}"; do
  DATA=${STAGED_FILES[$i]}
  pattern="src/"
  DATA=${DATA/$pattern/}
  STAGED_FILES[$i]=$DATA
done

#npm run lint --prefix . -- "${STAGED_FILES[@]}" --fix
yarn eslint "src/${STAGED_FILES[@]}"

ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
# git add "${FRONTEND_STAGED_FILES[@]}"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi

exit $?
