export enum PriceControlActionType {
  FETCHING = 'PRICE_CONTROL_FETCHING',
  FETCH_SUCCESS = 'PRICE_CONTROL_FETCH_SUCCESS',
  FETCH_ERROR = 'PRICE_CONTROL_FETCH_ERROR',
  UPDATING = 'PRICE_CONTROL_UPDATING',
  UPDATE_SUCCESS = 'PRICE_CONTROL_UPDATE_SUCCESS',
  UPDATE_ERROR = 'PRICE_CONTROL_UPDATE_ERROR',
  DELETING = 'PRICE_CONTROL_DELETING',
  DELETE_SUCCESS = 'PRICE_CONTROL_DELETE_SUCCESS',
  DELETE_ERROR = 'PRICE_CONTROL_DELETE_ERROR',
  CREATING = 'PRICE_CONTROL_CREATING',
  CREATE_SUCCESS = 'PRICE_CONTROL_CREATE_SUCCESS',
  CREATE_ERROR = 'PRICE_CONTROL_CREATE_ERROR',
}
