export enum PriceActionType {
  LOADING = 'PRICE_LOADING',
  LOADING_ERROR = 'PRICE_LOADING_ERROR',
  FETCH_SUCCESS = 'PRICE_FETCH_SUCCESS',
  UPDATE_SUCCESS = 'PRICE_UPDATE_SUCCESS',
  DELETE_SUCCESS = 'PRICE_DELETE_SUCCESS',
  CREATE_SUCCESS = 'PRICE_CREATE_SUCCESS',
}
