export enum ShopActionType {
  LOADING = 'SHOP_ITEM_LOADING',
  LOADING_ERROR = 'SHOP_ITEM_LOADING_ERROR',
  FETCH_SUCCESS = 'SHOP_ITEM_FETCH_SUCCESS',
  UPDATE_SUCCESS = 'SHOP_ITEM_UPDATE_SUCCESS',
  DELETE_SUCCESS = 'SHOP_ITEM_DELETE_SUCCESS',
  CREATE_SUCCESS = 'SHOP_ITEM_CREATE_SUCCESS',
}
