export enum ShoppingListActionType {
  FETCHING = 'SHOPPING_ITEM_FETCHING',
  FETCH_SUCCESS = 'SHOPPING_ITEM_FETCH_SUCCESS',
  FETCH_ERROR = 'SHOPPING_ITEM_FETCH_ERROR',
  UPDATING = 'SHOPPING_ITEM_UPDATING',
  UPDATE_SUCCESS = 'SHOPPING_ITEM_UPDATE_SUCCESS',
  UPDATE_ERROR = 'SHOPPING_ITEM_UPDATE_ERROR',
  DELETING = 'SHOPPING_ITEM_DELETING',
  DELETE_SUCCESS = 'SHOPPING_ITEM_DELETE_SUCCESS',
  DELETE_ERROR = 'SHOPPING_ITEM_DELETE_ERROR',
  CREATING = 'SHOPPING_ITEM_CREATING',
  CREATE_SUCCESS = 'SHOPPING_ITEM_CREATE_SUCCESS',
  CREATE_ERROR = 'SHOPPING_ITEM_CREATE_ERROR',
}
